---
# tasks file for java_role

- name: Java | Include OS family/distribution specific defaults
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ role_path }}/defaults/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/defaults/{{ ansible_os_family | lower }}.yml"
        - "main.yml"
      ignore_errors: true

- name: Java | Include OS family/distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ role_path }}/vars/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/vars/{{ ansible_os_family }}.yml"
        - "{{ role_path }}/vars/main.yml"
      ignore_errors: true

- name: Java | Include OS family/distribution specific tasks
  include: "{{ item }}"
  with_first_found:
    - files:
        - "{{ role_path }}/tasks/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/{{ ansible_os_family | lower }}.yml"
      skip: true


- name: Java | OpenJDK | Installation
  include_tasks: openjdk.yml
  when: java_source == 'openjdk'

- name: Java | Oracle | Installation
  include_tasks: oracle.yml
  when: java_source == 'oracle'
