---
# tasks file for java_role

- name: Java | Oracle | Determine if Java is already installed
  command: which java
  register: oracle_java_task_installed
  changed_when: oracle_java_task_installed.rc != 0
  failed_when: no
  check_mode: no
# oracle_java_installed.rc == 0 : installed
# oracle_java_installed.rc == 1 : not installed

- name: Java | Oracle | Set fact oracle_java_installed
  set_fact:
    oracle_java_installed={{ not oracle_java_task_installed.changed }}

- name: Java | Oracle | Determine which Java version is installed
  shell: |
    set -o pipefail |
    java -version 2>&1 |
    head -n 1 |
    awk '{ print $3 }' |
    awk -F '"' '{ print $2 }'
  register: oracle_java_task_version
  when: oracle_java_installed
  changed_when: False

- name: Java | Oracle | Set fact oracle_java_installed_version
  set_fact:
    oracle_java_version_installed="{{ oracle_java_task_version.stdout }}"
  when: oracle_java_task_version is defined and oracle_java_task_version.stdout is defined
  changed_when: False

- name: Java | Oracle | Download .tar.gz file containing binaries from Oracle website
  get_url:
    url: "{{ java_oraclejdk_urls[java_oraclejdk_version].url }}"
    dest: "/tmp/jdk-{{ java_oraclejdk_version }}.tar.gz"
    # That implies that you accept the Oracle Binary Code License Agreement for Java SE (http://www.oracle.com/technetwork/java/javase/terms/license/index.html)
    headers:
      Cookie: "oraclelicense=accept-securebackup-cookie"
    checksum: "sha256:{{ java_oraclejdk_urls[java_oraclejdk_version].sha256 }}"
  when: >
    (not oracle_java_installed) or
    (java_oraclejdk_version != oracle_java_version_installed)
  until: java_download is succeeded
  register: java_download

- name: Java | Oracle | Ensure installation dir exists
  file:
    path: "{{ java_oraclejdk_install_path }}"
    state: directory
    mode: '0755'

- name: Java | Oracle | Extract java package
  unarchive:
    src: "/tmp/jdk-{{ java_oraclejdk_version }}.tar.gz"
    dest: "{{ java_oraclejdk_install_path }}"
    remote_src: yes
    extra_opts: --strip-components=1
  when: java_download is changed
  notify: restart_services

- name: Java | Oracle | Setting OpenJDK home
  set_fact:
    java_home: "{{ java_oraclejdk_install_path }}"

- name: Java | Oracle | Export environment variables
  template:
    src: etc/profile.d/jdk_home.sh.j2
    dest: /etc/profile.d/jdk_home.sh

- name: Java | Oracle | Update alternatives
  alternatives:
    name: "{{ item }}"
    link: /usr/bin/{{ item }}
    path: "{{ java_oraclejdk_install_path }}/bin/{{ item }}"
  with_items:
    - "java"
    - "javac"
    - "jar"
