---
# tasks file for java_role

- name: Java | Oracle | Check Java version
  command: java -version
  register: java_check_version
  changed_when: false
  ignore_errors: true
  check_mode: no

- name: Java | Oracle | Download .tar.gz file containing binaries from Oracle website
  get_url:
    url: "{{ java_oraclejdk_urls[java_oraclejdk_version].url }}"
    dest: "/tmp/jdk-{{ java_oraclejdk_version }}.tar.gz"
    # That implies that you accept the Oracle Binary Code License Agreement for Java SE (http://www.oracle.com/technetwork/java/javase/terms/license/index.html)
    headers:
      Cookie: "oraclelicense=accept-securebackup-cookie"
    checksum: "sha256:{{ java_oraclejdk_urls[java_oraclejdk_version].sha256 }}"
  when: >
    (java_oraclejdk_version not in java_check_version.stderr) or
    (java_check_version is failed)
  until: java_download is succeeded
  register: java_download

- name: Java | Oracle | Ensure installation dir exists
  file:
    path: "{{ java_oraclejdk_install_path }}"
    state: directory
    mode: '0755'

- name: Java | Oracle | Extract java package
  unarchive:
    src: "/tmp/jdk-{{ java_oraclejdk_version }}.tar.gz"
    dest: "{{ java_oraclejdk_install_path }}"
    remote_src: yes
    extra_opts: --strip-components=1
  when: java_download is changed
  register: java_package_installed
  notify: restart_services

- name: Java | Oracle | Setting OpenJDK home
  set_fact:
    java_home: "{{ java_oraclejdk_install_path }}"

- name: Java | Oracle | Export environment variables
  template:
    src: etc/profile.d/jdk_home.sh.j2
    dest: /etc/profile.d/jdk_home.sh

- name: Java | Oracle | Update alternatives
  alternatives:
    name: "{{ item }}"
    link: /usr/bin/{{ item }}
    path: "{{ java_oraclejdk_install_path }}/bin/{{ item }}"
  with_items:
    - "java"
    - "javac"
    - "jar"
