---
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4-stretch
    working_directory: ~/jira_role
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            sudo pip install -r test-requirements.txt
      # run tests!
      - run:
          name: run tests
          command: |
            molecule test --all

      - store_artifacts:
          path: test-reports
          destination: test-reports
